# Generated by Django 2.2.12 on 2021-05-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_auto_20210511_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='object_id',
        ),
    ]
