# Generated by Django 2.2.12 on 2021-04-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_auto_20210421_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
