# Generated by Django 2.2.12 on 2021-04-20 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('date_created', models.TimeField(default=django.utils.timezone.now)),
                ('date_modified', models.TimeField(default=django.utils.timezone.now)),
                ('date_published', models.TimeField(default=django.utils.timezone.now)),
                ('point_good', models.IntegerField(default=0)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('postitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='q_and_a.PostItem')),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_to', to='q_and_a.PostItem')),
            ],
            bases=('q_and_a.postitem',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('postitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='q_and_a.PostItem')),
                ('title', models.CharField(default='', max_length=512)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_and_a.Comment')),
                ('tags', models.ManyToManyField(to='q_and_a.Tag')),
            ],
            bases=('q_and_a.postitem',),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('postitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='q_and_a.PostItem')),
                ('title', models.CharField(default='', max_length=512)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_comment', to='q_and_a.Comment')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_related_to', to='q_and_a.PostItem')),
                ('tags', models.ManyToManyField(to='q_and_a.Tag')),
            ],
            bases=('q_and_a.postitem',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('postitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='q_and_a.PostItem')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_and_a.Comment')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_and_a.Question')),
            ],
            bases=('q_and_a.postitem',),
        ),
    ]
