# Generated by Django 2.2.12 on 2021-05-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_answers',
            field=models.IntegerField(default=0),
        ),
    ]
