# Generated by Django 2.2.12 on 2021-05-11 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('q_and_a', '0002_question_num_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='good_posted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='a_good_posted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diary',
            name='good_posted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='d_good_posted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='good_posted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='q_good_posted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
