# Generated by Django 2.2.12 on 2021-04-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0002_auto_20210422_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comments',
        ),
    ]
