# Generated by Django 2.2.12 on 2021-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0004_auto_20210423_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
