# Generated by Django 2.2.12 on 2021-05-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0004_auto_20210511_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_modified']},
        ),
    ]
