# Generated by Django 2.2.12 on 2021-05-18 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('q_and_a', '0005_auto_20210518_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='good_posted_by',
            field=models.ManyToManyField(blank=True, related_name='c_good_posted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
