# Generated by Django 2.2.12 on 2021-05-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0006_comment_good_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
