# Generated by Django 2.2.12 on 2021-05-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0007_tag_is_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='q_and_a.Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='q_and_a.Tag'),
        ),
    ]
